version: "3"
services:
  springboot-app:
    container_name: spring-app
    image: springboot-app
    restart: always
    build: .
    ports:
      - 8082:8080
    environment:
      POSTGRES_HOST: postgresdb
      POSTGRES_USER: kirsing
      POSTGRES_PASSWORD: 219528k
      POSTGRES_PORT: 5432

  postgredb:
    container_name: postgresdb
    image: postgres
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: kirsing
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: 219528k